= Helm Tutorial

image:https://github.com/redhat-scholars/helm-tutorial/workflows/docs/badge.svg[]


You can access the HTML version of this tutorial here: https://redhat-scholars.github.io/helm-tutorial/[window="_blank"]

== Why Helm?

Helm is a packager for Kubernetes that bundles related manifest files and packages them into a single logical deployment unit: Chart. 

Simplified, for many engineers Helm makes it easy to start using Kubernetes with real applications. Helm Charts are useful for addressing the installation complexities and simple upgrades of particularly stateless applications like web apps. Say goodbye to the many, long, hard-coded yaml files and embrace an easier way to manage your deployed applications!

In this tutorial we will explore how to create, maintain and install Helm charts for different software. 


## Building the HTML locally

In the root of your git repository, run:

```
bin/build-site.sh
```

And then open your `gh-pages/index.html` file:

```
open gh-pages/index.html
```

## Iterative local development

You can develop the tutorial docs locally using a rapid iterative cycle.

First, install the `yarn` dependencies:

[source,bash]
----
yarn install
----

And now start `gulp`. It will create the website and open your browser connected with `browser-sync`. Everytime it detects a change, it will automatically refresh your browser page.

[source,bash]
----
gulp
----

You can clean the local cache using:

[source,bash]
----
gulp clean
----